<?php

namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Seeder;

class EnhancedClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            // Pessoas Físicas
            [
                'name' => 'João Silva Santos',
                'type' => Client::TYPE_INDIVIDUAL,
                'document' => '12345678901',
                'email' => 'joao.silva@email.com',
                'phone' => '11987654321',
                'responsible' => null,
                'responsible_email' => null,
                'responsible_phone' => null,
                'state_registration' => null,
                'municipal_registration' => null,
                'zip_code' => '01234567',
                'address' => 'Rua das Flores, 123',
                'number' => '123',
                'complement' => 'Apt 45',
                'neighborhood' => 'Centro',
                'city' => 'São Paulo',
                'state' => 'SP',
                'country' => 'Brasil',
                'status' => Client::STATUS_ACTIVE,
                'notes' => 'Cliente VIP, preferência por contato via WhatsApp. Desenvolve aplicativos mobile.',
            ],
            [
                'name' => 'Maria Oliveira Costa',
                'type' => Client::TYPE_INDIVIDUAL,
                'document' => '98765432100',
                'email' => 'maria.oliveira@gmail.com',
                'phone' => '21976543210',
                'responsible' => null,
                'responsible_email' => null,
                'responsible_phone' => null,
                'state_registration' => null,
                'municipal_registration' => null,
                'zip_code' => '22222222',
                'address' => 'Avenida Copacabana, 456',
                'number' => '456',
                'complement' => 'Cobertura',
                'neighborhood' => 'Copacabana',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'country' => 'Brasil',
                'status' => Client::STATUS_ACTIVE,
                'notes' => 'Arquiteta especializada em design de interiores. Projetos de alta qualidade.',
            ],
            [
                'name' => 'Carlos Eduardo Pereira',
                'type' => Client::TYPE_INDIVIDUAL,
                'document' => '11122233344',
                'email' => 'carlos.pereira@outlook.com',
                'phone' => '31988776655',
                'responsible' => null,
                'responsible_email' => null,
                'responsible_phone' => null,
                'state_registration' => null,
                'municipal_registration' => null,
                'zip_code' => '30112000',
                'address' => 'Rua Bahia, 789',
                'number' => '789',
                'complement' => null,
                'neighborhood' => 'Centro',
                'city' => 'Belo Horizonte',
                'state' => 'MG',
                'country' => 'Brasil',
                'status' => Client::STATUS_ACTIVE,
                'notes' => 'Consultor financeiro. Trabalha com investimentos e planejamento patrimonial.',
            ],

            // Pessoas Jurídicas
            [
                'name' => 'TechnoSoft Desenvolvimento Ltda',
                'type' => Client::TYPE_LEGAL,
                'document' => '12345678000195',
                'email' => 'contato@technosoft.com.br',
                'phone' => '1133334444',
                'responsible' => 'Roberto Lima',
                'responsible_email' => 'roberto.lima@technosoft.com.br',
                'responsible_phone' => '11999887766',
                'state_registration' => '123456789',
                'municipal_registration' => '987654321',
                'zip_code' => '04567890',
                'address' => 'Avenida Paulista, 1000',
                'number' => '1000',
                'complement' => 'Andar 15, Sala 1501',
                'neighborhood' => 'Bela Vista',
                'city' => 'São Paulo',
                'state' => 'SP',
                'country' => 'Brasil',
                'status' => Client::STATUS_ACTIVE,
                'notes' => 'Empresa de desenvolvimento de software corporativo. Especializada em ERP e CRM.',
            ],
            [
                'name' => 'Inovação Digital Solutions S.A.',
                'type' => Client::TYPE_LEGAL,
                'document' => '98765432000123',
                'email' => 'comercial@inovacaodigital.com',
                'phone' => '2133221100',
                'responsible' => 'Ana Carolina Mendes',
                'responsible_email' => 'ana.mendes@inovacaodigital.com',
                'responsible_phone' => '21988775544',
                'state_registration' => '987654321',
                'municipal_registration' => '123456789',
                'zip_code' => '22071900',
                'address' => 'Rua das Laranjeiras, 500',
                'number' => '500',
                'complement' => 'Sala 302',
                'neighborhood' => 'Laranjeiras',
                'city' => 'Rio de Janeiro',
                'state' => 'RJ',
                'country' => 'Brasil',
                'status' => Client::STATUS_ACTIVE,
                'notes' => 'Startup focada em transformação digital. Trabalha com IA e machine learning.',
            ],
            [
                'name' => 'MegaCorp Tecnologia Empresarial Ltda',
                'type' => Client::TYPE_LEGAL,
                'document' => '11223344000156',
                'email' => 'info@megacorp.com.br',
                'phone' => '4733445566',
                'responsible' => 'Fernando Silva',
                'responsible_email' => 'fernando.silva@megacorp.com.br',
                'responsible_phone' => '47999112233',
                'state_registration' => '456789123',
                'municipal_registration' => '654321987',
                'zip_code' => '88010100',
                'address' => 'Rua Felipe Schmidt, 200',
                'number' => '200',
                'complement' => 'Centro Empresarial, Torre A',
                'neighborhood' => 'Centro',
                'city' => 'Florianópolis',
                'state' => 'SC',
                'country' => 'Brasil',
                'status' => Client::STATUS_ACTIVE,
                'notes' => 'Empresa de grande porte. Soluções de automação industrial e IoT.',
            ],
            [
                'name' => 'StartupHub Aceleradora Ltda',
                'type' => Client::TYPE_LEGAL,
                'document' => '55667788000199',
                'email' => 'contato@startuphub.com',
                'phone' => '8533667788',
                'responsible' => 'Juliana Santos',
                'responsible_email' => 'juliana@startuphub.com',
                'responsible_phone' => '85988990011',
                'state_registration' => '789123456',
                'municipal_registration' => '321654987',
                'zip_code' => '60020181',
                'address' => 'Avenida Beira Mar, 3000',
                'number' => '3000',
                'complement' => 'Sala 1001',
                'neighborhood' => 'Meireles',
                'city' => 'Fortaleza',
                'state' => 'CE',
                'country' => 'Brasil',
                'status' => Client::STATUS_ACTIVE,
                'notes' => 'Aceleradora de startups. Foco em tecnologia e inovação para o Nordeste.',
            ],

            // Alguns clientes inativos para teste
            [
                'name' => 'Empresa Descontinuada Ltda',
                'type' => Client::TYPE_LEGAL,
                'document' => '99888777000166',
                'email' => 'contato@descontinuada.com',
                'phone' => '1144556677',
                'responsible' => 'Pedro Inativo',
                'responsible_email' => 'pedro@descontinuada.com',
                'responsible_phone' => '11944556677',
                'state_registration' => '999888777',
                'municipal_registration' => '777888999',
                'zip_code' => '08000000',
                'address' => 'Rua do Comércio, 100',
                'number' => '100',
                'complement' => null,
                'neighborhood' => 'Centro',
                'city' => 'Osasco',
                'state' => 'SP',
                'country' => 'Brasil',
                'status' => Client::STATUS_INACTIVE,
                'notes' => 'Cliente inativo desde janeiro de 2024. Empresa encerrou atividades.',
            ],
            [
                'name' => 'Cliente Suspenso Individual',
                'type' => Client::TYPE_INDIVIDUAL,
                'document' => '44455566677',
                'email' => 'suspenso@email.com',
                'phone' => '11888999000',
                'responsible' => null,
                'responsible_email' => null,
                'responsible_phone' => null,
                'state_registration' => null,
                'municipal_registration' => null,
                'zip_code' => '03000000',
                'address' => 'Rua da Suspensão, 50',
                'number' => '50',
                'complement' => 'Casa 2',
                'neighborhood' => 'Vila Suspensa',
                'city' => 'São Paulo',
                'state' => 'SP',
                'country' => 'Brasil',
                'status' => Client::STATUS_INACTIVE,
                'notes' => 'Cliente temporariamente suspenso por questões contratuais.',
            ],
        ];

        foreach ($clients as $clientData) {
            Client::create($clientData);
        }

        $this->command->info('Enhanced client data seeded successfully!');
        $this->command->info('Created:');
        $this->command->info('- ' . Client::byType(Client::TYPE_INDIVIDUAL)->count() . ' individual clients');
        $this->command->info('- ' . Client::byType(Client::TYPE_LEGAL)->count() . ' legal entity clients');
        $this->command->info('- ' . Client::active()->count() . ' active clients');
        $this->command->info('- ' . Client::inactive()->count() . ' inactive clients');
    }
}
