services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devnity_app
    restart: unless-stopped
    ports:
      # Expõe a aplicação na porta 8000
      - "8002:80"
    volumes:
      - .:/var/www/html
      # Monta a pasta compartilhada do Deployer com caminho absoluto para funcionar em qualquer contexto
      - /var/www/devnity/shared:/var/www/shared
      # Sobrepõe os symlinks com bind mounts diretos para garantir que Laravel enxergue storage e cache
      - /var/www/devnity/shared/storage:/var/www/html/storage
      - /var/www/devnity/shared/bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      # Conecta à sua rede principal já existente
      - rede_geral_existente
    env_file:
      - .env

networks:
  rede_geral_existente:
    external: true
    # Garanta que este é o nome exato da sua rede externa
    name: rede_dados_geral